version: '3.8'
services:
  mysql:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_DATABASE: fateflow
      MYSQL_ROOT_PASSWORD: fateflow
    volumes:
      - db-data:/var/lib/mysql
  fateflow:
    image: federatedai/fateflow:1.10.0-release
    restart: always
    depends_on:
      - mysql
    command:
      - /bin/sh
      - -c
      - |
        cat << EOF > conf/service_conf.yaml
        fateflow:
          host: 0.0.0.0
          http_port: 9380
          grpc_port: 9360
        database:
          name: fateflow
          user: root
          passwd: fateflow
          host: mysql
          port: 3306
        default_engines:
          computing: standalone
          federation: standalone
          storage: standalone  
        fateboard:
          host: fateboard
          port: 8080
        EOF
        python fateflow/python/fate_flow/fate_flow_server.py

    ports:
      - "9380:9380"
  fateboard:
    image: federatedai/fateboard:1.10.0-release
    restart: always
    depends_on:
      - fateflow
    command: ["java", "-jar", "fateboard.jar"]
    environment:
      fateflow.url: http://fateflow:9380
      fateboard.datasource.jdbc-url: jdbc:mysq://mysql:3360/fateflow
      fateboard.datasource.username: root
      fateboard.datasource.password: fateflow
    ports:
      - "8080:8080"
volumes:
  db-data:
